---
title: "Nonlinear dCor"
output: html_notebook
---

# Nonlinear Method (dCOr)

```{r}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
library(data.table)
library(tibble)
library(WGCNA)
library(ggplot2)
options(stringsAsFactors = FALSE)
disableWGCNAThreads()
```

# 1 Soft-thresholding

## 1.1 Healthy Samples

```{r}
healthy.dcor = fread("dcor/dcor_nonsepsis.csv", header=T, showProgress=T)
healthy.dcor = as.matrix(healthy.dcor[,-c(1)])
dim(healthy.dcor)
```

```{r}
sft = pickSoftThreshold.fromSimilarity(
    healthy.dcor,
    powerVector = c(seq(1, 10, by = 1)),
    removeFirst = FALSE, nBreaks = 10, blockSize = 2000,
    moreNetworkConcepts=FALSE,RsquaredCut = 0.90,
    verbose = 5, indent = 0)
sft$powerEstimate
```

```{r}
adj.healthy = adjacency.fromSimilarity(healthy.dcor, power=1)
dim(adj.healthy)
hist(rowSums(adj.healthy))

adj.healthy = adjacency.fromSimilarity(healthy.dcor, power=sft$powerEstimate)
dim(adj.healthy)
hist(rowSums(adj.healthy))
```

## 1.2 Diseased Samples

```{r}
diseased.dcor = fread("dcor/dcor_sepsis.csv", header=T, showProgress=T)
diseased.dcor = as.matrix(diseased.dcor[,-c(1)])
dim(diseased.dcor)
```

```{r}
sft = pickSoftThreshold.fromSimilarity(
    diseased.dcor,
    powerVector = c(seq(1, 10, by = 1)),
    removeFirst = FALSE, nBreaks = 10, blockSize = 2000,
    moreNetworkConcepts=FALSE, RsquaredCut = 0.90,
    verbose = 5, indent = 0)
sft$powerEstimate
```

```{r}
adj.diseased = adjacency.fromSimilarity(diseased.dcor, power=1)
dim(adj.diseased)
hist(rowSums(adj.diseased))

adj.diseased = adjacency.fromSimilarity(diseased.dcor, power=sft$powerEstimate)
dim(adj.diseased)
hist(rowSums(adj.diseased))
```

## 1.3 Nonshock Samples

```{r}
nonshock.dcor = fread("dcor/dcor_preshock.csv", header=T, showProgress=T)
nonshock.dcor = as.matrix(nonshock.dcor[,-c(1)])
dim(nonshock.dcor)
```

```{r}
sft = pickSoftThreshold.fromSimilarity(
    nonshock.dcor,
    powerVector = c(seq(1, 10, by = 1)),
    removeFirst = FALSE, nBreaks = 10, blockSize = 2000,
    moreNetworkConcepts=FALSE, RsquaredCut = 0.90,
    verbose = 5, indent = 0)
sft$powerEstimate
```

```{r}
adj.nonshock = adjacency.fromSimilarity(nonshock.dcor, power=1)
dim(adj.nonshock)
hist(rowSums(adj.nonshock))

adj.nonshock = adjacency.fromSimilarity(nonshock.dcor, power=sft$powerEstimate)
dim(adj.nonshock)
hist(rowSums(adj.nonshock))
```

## 1.4 Shock Samples

```{r}
shock.dcor = fread("dcor/dcor_shock.csv", header=T, showProgress=T)
shock.dcor = as.matrix(shock.dcor[,-c(1)])
dim(shock.dcor)
```

```{r}
sft = pickSoftThreshold.fromSimilarity(
    shock.dcor,
    powerVector = c(seq(1, 10, by = 1)),
    removeFirst = FALSE, nBreaks = 10, blockSize = 2000,
    moreNetworkConcepts=FALSE, RsquaredCut = 0.90,
    verbose = 5, indent = 0)
sft$powerEstimate
```

```{r}
adj.shock = adjacency.fromSimilarity(shock.dcor, power=1)
dim(adj.shock)
hist(rowSums(adj.shock))

adj.shock = adjacency.fromSimilarity(shock.dcor, power=sft$powerEstimate)
dim(adj.shock)
hist(rowSums(adj.shock))
```

# 2 Scale-free Networks

```{r}
network_path = "scale-free-networks/"
module_path = "modules/"
dcor_path = "dcor/"
genexdata_path = "genexdata/"
```

## 1 Healthy Modules

```{r}
healthy.dcor = fread(paste0(dcor_path,"healthy_scalefree10.csv"), header=T, showProgress=T)
healthy.dcor = as.matrix(healthy.dcor[,-c(1)])
dim(healthy.dcor)
```

```{r}
TOM.healthy.dcor = TOMsimilarity(as.matrix(healthy.dcor));
dissTOM.healthy.dcor = 1-TOM.healthy.dcor
dim(TOM.healthy.dcor)
```

```{r}
hist(rowSums(TOM.healthy.dcor))
```

```{r}
write.table(dissTOM.healthy.dcor, file = paste0(network_path,"dissTOM_healthy_dcor10.txt"), row.names = FALSE, col.names = FALSE, sep = " ")
```

```{r}
# Call the hierarchical clustering function
geneTree = hclust(as.dist(dissTOM.healthy.dcor), method = "average");
# Plot the resulting clustering tree (dendrogram)
sizeGrWindow(12,9)
plot(geneTree, xlab="", sub="", 
     main = "Gene clustering of Healthy Samples based on TOM-based dissimilarity",
     labels = FALSE)

# We like large modules, so we set the minimum module size relatively high:
minModuleSize = 30;

# Module identification using dynamic tree cut:
dynamicMods = cutreeDynamic(dendro = geneTree, distM = dissTOM.healthy.dcor,
                            deepSplit = 2, pamRespectsDendro = FALSE,
                            minClusterSize = minModuleSize)
table(dynamicMods)

# Convert numeric lables into colors
dynamicColors = labels2colors(dynamicMods)
table(dynamicColors)

# Plot the dendrogram and colors underneath
sizeGrWindow(8,6)
plotDendroAndColors(geneTree, dynamicColors, "Dynamic Tree Cut",
dendroLabels = FALSE, hang = 0.03,
addGuide = TRUE, guideHang = 0.05,
main = "Gene dendrogram of HealthySamples")
```

```{r}
healthy.ggset = read.table(paste0(genexdata_path,"genex2_nonsepsis.txt"), header = TRUE, sep="\t")
rownames(healthy.ggset) = healthy.ggset$Genes
healthy.ggset = as.data.frame(t(healthy.ggset[,-1]))
healthy.ggset = healthy.ggset[,colnames(healthy.dcor)]
head(healthy.ggset)

# Calculate eigengenes
MEList = moduleEigengenes(as.matrix(healthy.ggset), colors = dynamicColors)
MEs = MEList$eigengenes
# Calculate dissimilarity of module eigengenes
MEDiss = 1-cor(MEs);
# Cluster module eigengenes
METree = hclust(as.dist(MEDiss), method = "average");
# Plot the result
sizeGrWindow(16, 8)
plot(METree, main = "Clustering of module eigengenes in Healthy Samples",
xlab = "", sub = "")
# Merging modules
MEDissThres = 0.2
# Plot the cut line into the dendrogram
abline(h=MEDissThres, col = "red")
```

```{r}
# Call an automatic merging function
merge = mergeCloseModules(as.matrix(healthy.ggset), dynamicColors, cutHeight = MEDissThres, verbose = 3)
# The merged module colors
mergedColors = merge$colors
# Eigengenes of the new merged modules:
mergedMEs = merge$newMEs

sizeGrWindow(12, 9)
#pdf(file = "Plots/geneDendro-3.pdf", wi = 9, he = 6)
png("Dendogram_Healthy.png",width=7,height=5,units="in",res=600)
plotDendroAndColors(geneTree, cbind(dynamicColors, mergedColors),
c("Dynamic Tree Cut", "Merged dynamic"),
dendroLabels = FALSE, hang = 0.03,
addGuide = TRUE, guideHang = 0.05)

```

```{r}
# Rename to moduleColors
moduleColors = mergedColors
# Construct numerical labels corresponding to the colors
colorOrder = c("grey", standardColors(50));
moduleLabels = match(moduleColors, colorOrder)-1;
MEs = mergedMEs
dim(MEs)

freq.tab <- as.data.frame(table(moduleColors))

colnames(freq.tab) <- c("Modules", "Membership")
freq.tab = freq.tab[order(-freq.tab$Membership), ]
rownames(freq.tab) <- 1:nrow(freq.tab)
freq.tab$Modules = factor(freq.tab$Modules, levels = freq.tab$Modules)

ggplot(freq.tab, aes(x = Modules, y = Membership, fill = Modules)) +
  geom_bar(stat = "identity",  color = "grey1", size = 0.5) +
  labs(title = "Module Size in Healthy Patients",
       x = "Modules",
       y = "Membership") +
  scale_fill_manual(values=as.character(freq.tab$Modules)) + # Set bar colors
  theme_minimal() + 
  theme(
    panel.grid = element_blank(),        # Remove grid lines
    axis.line = element_line(size = 0.5),  # Adjust line width of axes
    axis.text.x = element_text(size = 10, color='black', angle = 90), # Adjust font size of axis text
    axis.text.y = element_text(size = 10, color='black'),
    axis.title = element_text(size = 16) # Adjust font size of axis labels
  ) +
  theme(legend.position = "none")  # Remove legend if unnecessary
```

```{r}
# Function to extract genes belonging to each module
genelist = names(healthy.ggset)
get_module_genes <- function(genelist, moduleColors) {
  unique_colors <- unique(moduleColors) # Get unique module names
  module_genes <- lapply(unique_colors, function(color) {
    which(moduleColors == color) # Indices of genes in this module
  })
  names(module_genes) <- unique_colors
  # Map indices back to gene names
  module_genes <- lapply(module_genes, function(indices) genelist[indices])
  return(module_genes)
}

healthy_modules <- get_module_genes(colnames(healthy.dcor), moduleColors)

# Create a dataframe
df <- data.frame(
  genes = colnames(healthy.dcor),
  modules = moduleColors
)
# Save the dataframe to a CSV file
output_file <- paste0(module_path,"modules_healthy_scalefree10.csv")
write.csv(df, file = output_file, row.names = F)
length(df$genes)
unique(df$modules)
head(df)
```

## 2 Diseased Modules

```{r}
diseased.dcor = fread(paste0(dcor_path,"diseased_scalefree6.csv"), header=T, showProgress=T)
diseased.dcor = as.matrix(diseased.dcor[,-c(1)])
dim(diseased.dcor)
```

```{r}
TOM.diseased.dcor = TOMsimilarity(as.matrix(diseased.dcor));
dissTOM.diseased.dcor = 1-TOM.diseased.dcor
dim(TOM.diseased.dcor)
```

```{r}
hist(rowSums(TOM.diseased.dcor))
```

```{r}
write.table(dissTOM.diseased.dcor, file = paste0(network_path,"dissTOM_diseased_dcor6.txt"), row.names = FALSE, col.names = FALSE, sep = " ")
```

```{r}
# Call the hierarchical clustering function
geneTree2 = hclust(as.dist(dissTOM.diseased.dcor), method = "average");
# Plot the resulting clustering tree (dendrogram)
sizeGrWindow(12,9)
plot(geneTree2, xlab="", sub="", 
     main = "Gene clustering of Diseased Samples based on TOM-based dissimilarity",
     labels = FALSE)

# We like large modules, so we set the minimum module size relatively high:
minModuleSize = 30;

# Module identification using dynamic tree cut:
dynamicMods2 = cutreeDynamic(dendro = geneTree2, distM = dissTOM.diseased.dcor,
                            deepSplit = 2, pamRespectsDendro = FALSE,
                            minClusterSize = minModuleSize)
table(dynamicMods2)

# Convert numeric lables into colors
dynamicColors2 = labels2colors(dynamicMods2)
table(dynamicColors2)

# Plot the dendrogram and colors underneath
sizeGrWindow(8,6)
plotDendroAndColors(geneTree2, dynamicColors2, "Dynamic Tree Cut",
dendroLabels = FALSE, hang = 0.03,
addGuide = TRUE, guideHang = 0.05,
main = "Gene dendrogram of Diseased Samples")
```

```{r}
diseased.ggset = read.table(paste0(genexdata_path,"genex2_sepsis.txt"), header = TRUE, sep="\t")
rownames(diseased.ggset) = diseased.ggset$Genes
diseased.ggset = as.data.frame(t(diseased.ggset[,-1]))
diseased.ggset = diseased.ggset[,colnames(diseased.dcor)]
head(diseased.ggset)

# Calculate eigengenes
MEList2 = moduleEigengenes(as.matrix(diseased.ggset), colors = dynamicColors2)
MEs2 = MEList2$eigengenes
# Calculate dissimilarity of module eigengenes
MEDiss2 = 1-cor(MEs2);
# Cluster module eigengenes
METree2 = hclust(as.dist(MEDiss2), method = "average");
# Plot the result
sizeGrWindow(16, 8)
plot(METree2, main = "Clustering of module eigengenes in Diseased Samples",
xlab = "", sub = "")
# Merging modules
MEDissThres = 0.2
# Plot the cut line into the dendrogram
abline(h=MEDissThres, col = "red")
```

```{r}
# Call an automatic merging function
merge2 = mergeCloseModules(as.matrix(diseased.ggset), dynamicColors2, cutHeight = MEDissThres, verbose = 3)
# The merged module colors
mergedColors2 = merge2$colors
# Eigengenes of the new merged modules:
mergedMEs2 = merge2$newMEs

sizeGrWindow(12, 9)
#pdf(file = "Plots/geneDendro-3.pdf", wi = 9, he = 6)
png("Dendogram_Diseased.png",width=7,height=5,units="in",res=600)
plotDendroAndColors(geneTree2, cbind(dynamicColors2, mergedColors2),
c("Dynamic Tree Cut", "Merged dynamic"),
dendroLabels = FALSE, hang = 0.03,
addGuide = TRUE, guideHang = 0.05)
```

```{r}
# Rename to moduleColors
moduleColors2 = mergedColors2
# Construct numerical labels corresponding to the colors
colorOrder2 = c("grey", standardColors(50));
moduleLabels2 = match(moduleColors2, colorOrder2)-1;
MEs2 = mergedMEs2
dim(MEs2)

freq.tab <- as.data.frame(table(moduleColors2))

colnames(freq.tab) <- c("Modules", "Membership")
freq.tab = freq.tab[order(-freq.tab$Membership), ]
rownames(freq.tab) <- 1:nrow(freq.tab)
freq.tab$Modules = factor(freq.tab$Modules, levels = freq.tab$Modules)

ggplot(freq.tab, aes(x = Modules, y = Membership, fill = Modules)) +
  geom_bar(stat = "identity",  color = "grey1", size = 0.5) +
  labs(title = "Module Size in Diseased Patients",
       x = "Modules",
       y = "Membership") +
  scale_fill_manual(values=as.character(freq.tab$Modules)) + # Set bar colors
  theme_minimal() + 
  theme(
    panel.grid = element_blank(),        # Remove grid lines
    axis.line = element_line(size = 0.5),  # Adjust line width of axes
    axis.text.x = element_text(size = 10, color='black', angle = 90), # Adjust font size of axis text
    axis.text.y = element_text(size = 10, color='black'),
    axis.title = element_text(size = 16) # Adjust font size of axis labels
  ) +
  theme(legend.position = "none")  # Remove legend if unnecessary
```

```{r}
# Function to extract genes belonging to each module
genelist = names(healthy.ggset)
get_module_genes <- function(genelist, moduleColors) {
  unique_colors <- unique(moduleColors) # Get unique module names
  module_genes <- lapply(unique_colors, function(color) {
    which(moduleColors == color) # Indices of genes in this module
  })
  names(module_genes) <- unique_colors
  # Map indices back to gene names
  module_genes <- lapply(module_genes, function(indices) genelist[indices])
  return(module_genes)
}

diseased_modules <- get_module_genes(colnames(diseased.dcor), moduleColors2)

# Create a dataframe
df <- data.frame(
  genes = colnames(diseased.dcor),
  modules = moduleColors2
)
# Save the dataframe to a CSV file
output_file <- paste0(module_path,"modules_diseased_scalefree6.csv")
write.csv(df, file = output_file, row.names = F)
dim(df)
head(df)
```

## 3 Non-shock Modules

```{r}
nonshock.dcor = fread(paste0(dcor_path,"nonshock_scalefree5.csv"), header=T, showProgress=T)
nonshock.dcor = as.matrix(nonshock.dcor[,-c(1)])
dim(nonshock.dcor)
```

```{r}
TOM.nonshock.dcor = TOMsimilarity(as.matrix(nonshock.dcor));
dissTOM.nonshock.dcor = 1-TOM.nonshock.dcor
dim(TOM.nonshock.dcor)
```

```{r}
write.table(dissTOM.nonshock.dcor, file = paste0(network_path,"dissTOM_nonshock_dcor5.txt"), row.names = FALSE, col.names = FALSE, sep = " ")
```

```{r}
# Call the hierarchical clustering function
geneTree3 = hclust(as.dist(dissTOM.nonshock.dcor), method = "average");
# Plot the resulting clustering tree (dendrogram)
sizeGrWindow(12,9)
plot(geneTree3, xlab="", sub="", 
     main = "Gene clustering of Nonshock Samples based on TOM-based dissimilarity",
     labels = FALSE)

# We like large modules, so we set the minimum module size relatively high:
minModuleSize = 30;

# Module identification using dynamic tree cut:
dynamicMods3 = cutreeDynamic(dendro = geneTree3, distM = dissTOM.nonshock.dcor,
                            deepSplit = 2, pamRespectsDendro = FALSE,
                            minClusterSize = minModuleSize)
table(dynamicMods3)

# Convert numeric lables into colors
dynamicColors3 = labels2colors(dynamicMods3)
table(dynamicColors3)

# Plot the dendrogram and colors underneath
sizeGrWindow(8,6)
plotDendroAndColors(geneTree3, dynamicColors3, "Dynamic Tree Cut",
dendroLabels = FALSE, hang = 0.03,
addGuide = TRUE, guideHang = 0.05,
main = "Gene dendrogram of Nonshock Samples")
```

```{r}
nonshock.ggset = read.table(paste0(genexdata_path,"genex2_preshock.txt"), header = TRUE, sep="\t")
rownames(nonshock.ggset) = nonshock.ggset$Genes
nonshock.ggset = as.data.frame(t(nonshock.ggset[,-1]))
nonshock.ggset = nonshock.ggset[,colnames(nonshock.dcor)]
head(nonshock.ggset)

# Calculate eigengenes
MEList3 = moduleEigengenes(as.matrix(nonshock.ggset), colors = dynamicColors3)
MEs3 = MEList3$eigengenes
# Calculate dissimilarity of module eigengenes
MEDiss3 = 1-cor(MEs3);
# Cluster module eigengenes
METree3 = hclust(as.dist(MEDiss3), method = "average");
# Plot the result
sizeGrWindow(16, 8)
plot(METree3, main = "Clustering of module eigengenes in Nonshock Samples",
xlab = "", sub = "")
# Merging modules
MEDissThres = 0.2
# Plot the cut line into the dendrogram
abline(h=MEDissThres, col = "red")
```

```{r}
# Call an automatic merging function
merge3 = mergeCloseModules(as.matrix(nonshock.ggset), dynamicColors3, cutHeight = MEDissThres, verbose = 3)
# The merged module colors
mergedColors3 = merge3$colors
# Eigengenes of the new merged modules:
mergedMEs3 = merge3$newMEs

sizeGrWindow(12, 9)
#pdf(file = "Plots/geneDendro-3.pdf", wi = 9, he = 6)
png("Dendogram_Nonshock.png",width=7,height=5,units="in",res=600)
plotDendroAndColors(geneTree3, cbind(dynamicColors3, mergedColors3),
c("Dynamic Tree Cut", "Merged dynamic"),
dendroLabels = FALSE, hang = 0.03,
addGuide = TRUE, guideHang = 0.05)
```

```{r}
# Rename to moduleColors
moduleColors3 = mergedColors3
# Construct numerical labels corresponding to the colors
colorOrder3 = c("grey", standardColors(50));
moduleLabels3 = match(moduleColors3, colorOrder3)-1;
MEs3 = mergedMEs3
dim(MEs3)

freq.tab <- as.data.frame(table(moduleColors3))

colnames(freq.tab) <- c("Modules", "Membership")
freq.tab = freq.tab[order(-freq.tab$Membership), ]
rownames(freq.tab) <- 1:nrow(freq.tab)
freq.tab$Modules = factor(freq.tab$Modules, levels = freq.tab$Modules)

ggplot(freq.tab, aes(x = Modules, y = Membership, fill = Modules)) +
  geom_bar(stat = "identity",  color = "grey1", size = 0.5) +
  labs(title = "Module Size in Nonshock Patients",
       x = "Modules",
       y = "Membership") +
  scale_fill_manual(values=as.character(freq.tab$Modules)) + # Set bar colors
  theme_minimal() + 
  theme(
    panel.grid = element_blank(),        # Remove grid lines
    axis.line = element_line(size = 0.5),  # Adjust line width of axes
    axis.text.x = element_text(size = 10, color='black', angle = 90), # Adjust font size of axis text
    axis.text.y = element_text(size = 10, color='black'),
    axis.title = element_text(size = 16) # Adjust font size of axis labels
  ) +
  theme(legend.position = "none")  # Remove legend if unnecessary
```

```{r}
# Function to extract genes belonging to each module
genelist = names(nonshock.ggset)
get_module_genes <- function(genelist, moduleColors) {
  unique_colors <- unique(moduleColors) # Get unique module names
  module_genes <- lapply(unique_colors, function(color) {
    which(moduleColors == color) # Indices of genes in this module
  })
  names(module_genes) <- unique_colors
  # Map indices back to gene names
  module_genes <- lapply(module_genes, function(indices) genelist[indices])
  return(module_genes)
}

nonshock_modules <- get_module_genes(colnames(nonshock.dcor), moduleColors3)

# Create a dataframe
df <- data.frame(
  genes = colnames(nonshock.dcor),
  modules = moduleColors3
)
# Save the dataframe to a CSV file
output_file <- paste0(module_path,"modules_nonshock_scalefree5.csv")
write.csv(df, file = output_file, row.names = F)
dim(df)
head(df)
```

## 4 Shock Modules

```{r}
shock.dcor = fread(paste0(dcor_path,"shock_scalefree8.csv"), header=T, showProgress=T)
shock.dcor = as.matrix(shock.dcor[,-c(1)])
dim(shock.dcor)
```

```{r}
TOM.shock.dcor = TOMsimilarity(as.matrix(shock.dcor));
dissTOM.shock.dcor = 1-TOM.shock.dcor
dim(TOM.shock.dcor)
```

```{r}
write.table(dissTOM.shock.dcor, file = paste0(network_path,"dissTOM_shock_dcor8.txt"), row.names = FALSE, col.names = FALSE, sep = " ")
```

```{r}
# Call the hierarchical clustering function
geneTree4 = hclust(as.dist(dissTOM.shock.dcor), method = "average");
# Plot the resulting clustering tree (dendrogram)
sizeGrWindow(12,9)
plot(geneTree4, xlab="", sub="", 
     main = "Gene clustering of Shock Samples based on TOM-based dissimilarity",
     labels = FALSE)

# We like large modules, so we set the minimum module size relatively high:
minModuleSize = 30;

# Module identification using dynamic tree cut:
dynamicMods4 = cutreeDynamic(dendro = geneTree4, distM = dissTOM.shock.dcor,
                            deepSplit = 2, pamRespectsDendro = FALSE,
                            minClusterSize = minModuleSize)
table(dynamicMods4)

# Convert numeric lables into colors
dynamicColors4 = labels2colors(dynamicMods4)
table(dynamicColors4)

# Plot the dendrogram and colors underneath
sizeGrWindow(8,6)
plotDendroAndColors(geneTree4, dynamicColors4, "Dynamic Tree Cut",
dendroLabels = FALSE, hang = 0.03,
addGuide = TRUE, guideHang = 0.05,
main = "Gene dendrogram of Shock Samples")
```

```{r}
shock.ggset = read.table(paste0(genexdata_path,"genex2_shock.txt"), header = TRUE, sep="\t")
rownames(shock.ggset) = shock.ggset$Genes
shock.ggset = as.data.frame(t(shock.ggset[,-1]))
shock.ggset = shock.ggset[,colnames(shock.dcor)]
head(shock.ggset)

# Calculate eigengenes
MEList4 = moduleEigengenes(as.matrix(shock.ggset), colors = dynamicColors4)
MEs4 = MEList4$eigengenes
# Calculate dissimilarity of module eigengenes
MEDiss4 = 1-cor(MEs4);
# Cluster module eigengenes
METree4 = hclust(as.dist(MEDiss4), method = "average");
# Plot the result
sizeGrWindow(16, 8)
plot(METree4, main = "Clustering of module eigengenes in Shock Samples",
xlab = "", sub = "")
# Merging modules
MEDissThres = 0.5
# Plot the cut line into the dendrogram
abline(h=MEDissThres, col = "red")
```

```{r}
# Call an automatic merging function
merge4 = mergeCloseModules(as.matrix(shock.ggset), dynamicColors4, cutHeight = MEDissThres, verbose = 3)
# The merged module colors
mergedColors4 = merge4$colors
# Eigengenes of the new merged modules:
mergedMEs4 = merge4$newMEs

sizeGrWindow(12, 9)
#pdf(file = "Plots/geneDendro-3.pdf", wi = 9, he = 6)
png("Dendogram_Shock.png",width=7,height=5,units="in",res=600)
plotDendroAndColors(geneTree4, cbind(dynamicColors4, mergedColors4),
c("Dynamic Tree Cut", "Merged dynamic"),
dendroLabels = FALSE, hang = 0.03,
addGuide = TRUE, guideHang = 0.05)
```

```{r}
# Rename to moduleColors
moduleColors4 = mergedColors4
# Construct numerical labels corresponding to the colors
colorOrder4 = c("grey", standardColors(50));
moduleLabels4 = match(moduleColors4, colorOrder4)-1;
MEs4 = mergedMEs4
dim(MEs4)

freq.tab <- as.data.frame(table(moduleColors4))

colnames(freq.tab) <- c("Modules", "Membership")
freq.tab = freq.tab[order(-freq.tab$Membership), ]
rownames(freq.tab) <- 1:nrow(freq.tab)
freq.tab$Modules = factor(freq.tab$Modules, levels = freq.tab$Modules)

ggplot(freq.tab, aes(x = Modules, y = Membership, fill = Modules)) +
  geom_bar(stat = "identity",  color = "grey1", size = 0.5) +
  labs(title = "Module Size in Shock Patients",
       x = "Modules",
       y = "Membership") +
  scale_fill_manual(values=as.character(freq.tab$Modules)) + # Set bar colors
  theme_minimal() + 
  theme(
    panel.grid = element_blank(),        # Remove grid lines
    axis.line = element_line(size = 0.5),  # Adjust line width of axes
    axis.text.x = element_text(size = 10, color='black', angle = 90), # Adjust font size of axis text
    axis.text.y = element_text(size = 10, color='black'),
    axis.title = element_text(size = 16) # Adjust font size of axis labels
  ) +
  theme(legend.position = "none")  # Remove legend if unnecessary

```

```{r}
# Function to extract genes belonging to each module
genelist = names(shock.ggset)
get_module_genes <- function(genelist, moduleColors) {
  unique_colors <- unique(moduleColors) # Get unique module names
  module_genes <- lapply(unique_colors, function(color) {
    which(moduleColors == color) # Indices of genes in this module
  })
  names(module_genes) <- unique_colors
  # Map indices back to gene names
  module_genes <- lapply(module_genes, function(indices) genelist[indices])
  return(module_genes)
}

nonshock_modules <- get_module_genes(colnames(shock.dcor), moduleColors4)

# Create a dataframe
df <- data.frame(
  genes = colnames(shock.dcor),
  modules = moduleColors4
)
# Save the dataframe to a CSV file
output_file <- paste0(module_path,"modules_shock_scalefree8.csv")
write.csv(df, file = output_file, row.names = F)
dim(df)
head(df)
```

# 3 GO Enrichment Analysis

```{r}
# Load the necessary libraries
library(clusterProfiler)
library(org.Hs.eg.db)  # Human gene annotations
library(enrichplot)     # For visualization
library(ggplot2)        # For plotting
```

## 3.1 Healthy vs Diseased Modules

```{r}
modules.df = read.csv("modules/modules_healthy_scalefree10.csv", header = T)
modules.df.2 = read.csv("modules/modules_diseased_scalefree6.csv", header = T)
head(modules.df)
head(modules.df.2)
```

```{r}
mod1 = "green"
state = "Healthy Samples"
genes = modules.df[modules.df$modules==mod1,]$genes

ego_bp <- enrichGO(
  gene         = genes, 
  OrgDb        = org.Hs.eg.db, 
  keyType      = "SYMBOL", 
  ont          = "BP",        # Choose BP (Biological Process), MF, or CC
  pAdjustMethod = "BH",       # Benjamini-Hochberg correction
  pvalueCutoff = 0.05, 
  qvalueCutoff = 0.05
)

# View top enriched GO terms
head(ego_bp)
write.csv(as.data.frame(ego_bp), paste0(mod1,"_healthy_modules.csv"))

# Example barplot
title = sprintf("Top GO BP Terms for %s", state)
gplot <- barplot(ego_bp, showCategory=10, title=title, ) + 
  geom_bar(stat="identity", color="black") +
         scale_fill_gradient(low = mod1, high = "gray90")  # Change color gradient

print(gplot)

mod1 = "magenta"
state = "Diseased Samples"
genes.2 = modules.df.2[modules.df.2$modules==mod1,]$genes

ego_bp.2 <- enrichGO(
  gene         = genes.2, 
  OrgDb        = org.Hs.eg.db, 
  keyType      = "SYMBOL", 
  ont          = "BP",        # Choose BP (Biological Process), MF, or CC
  pAdjustMethod = "BH",       # Benjamini-Hochberg correction
  pvalueCutoff = 0.05, 
  qvalueCutoff = 0.05
)

# View top enriched GO terms
head(ego_bp.2)
write.csv(as.data.frame(ego_bp.2), paste0(mod1,"_diseased_modules.csv"))


# Example barplot
title = sprintf("Top GO BP Terms for %s", state)
gplot <- barplot(ego_bp.2, showCategory=10, title=title, ) + 
  geom_bar(stat="identity", color="black") +
         scale_fill_gradient(low = mod1, high = "gray90")  # Change color gradient

print(gplot)
```

```{r}
mod1 = "grey"
state = "Healthy Samples"
genes = modules.df[modules.df$modules==mod1,]$genes

ego_bp <- enrichGO(
  gene         = genes, 
  OrgDb        = org.Hs.eg.db, 
  keyType      = "SYMBOL", 
  ont          = "BP",        # Choose BP (Biological Process), MF, or CC
  pAdjustMethod = "BH",       # Benjamini-Hochberg correction
  pvalueCutoff = 0.05, 
  qvalueCutoff = 0.05
)

# View top enriched GO terms
head(ego_bp)
write.csv(as.data.frame(ego_bp), paste0(mod1,"_healthy_modules.csv"))

# Example barplot
title = sprintf("Top GO BP Terms for %s", state)
gplot <- barplot(ego_bp, showCategory=10, title=title, ) + 
  geom_bar(stat="identity", color="black") +
         scale_fill_gradient(low = mod1, high = "gray90")  # Change color gradient

print(gplot)

mod1 = "turquoise"
state = "Diseased Samples"
genes.2 = modules.df.2[modules.df.2$modules==mod1,]$genes

ego_bp.2 <- enrichGO(
  gene         = genes.2, 
  OrgDb        = org.Hs.eg.db, 
  keyType      = "SYMBOL", 
  ont          = "BP",        # Choose BP (Biological Process), MF, or CC
  pAdjustMethod = "BH",       # Benjamini-Hochberg correction
  pvalueCutoff = 0.05, 
  qvalueCutoff = 0.05
)

# View top enriched GO terms
head(ego_bp.2)
write.csv(as.data.frame(ego_bp.2), paste0(mod1,"_diseased_modules.csv"))


# Example barplot
title = sprintf("Top GO BP Terms for %s", state)
gplot <- barplot(ego_bp.2, showCategory=10, title=title, ) + 
  geom_bar(stat="identity", color="black") +
         scale_fill_gradient(low = mod1, high = "gray90")  # Change color gradient

print(gplot)
```

```{r}
mod1 = "yellow"
state = "Healthy Samples"
genes = modules.df[modules.df$modules==mod1,]$genes

ego_bp <- enrichGO(
  gene         = genes, 
  OrgDb        = org.Hs.eg.db, 
  keyType      = "SYMBOL", 
  ont          = "BP",        # Choose BP (Biological Process), MF, or CC
  pAdjustMethod = "BH",       # Benjamini-Hochberg correction
  pvalueCutoff = 0.05, 
  qvalueCutoff = 0.05
)

# View top enriched GO terms
head(ego_bp)
write.csv(as.data.frame(ego_bp), paste0(mod1,"_healthy_modules.csv"))
# Example barplot
title = sprintf("Top GO BP Terms for %s", state)
gplot <- barplot(ego_bp, showCategory=10, title=title, ) + 
  geom_bar(stat="identity", color="black") +
         scale_fill_gradient(low = mod1, high = "gray90")  # Change color gradient

print(gplot)

mod1 = "turquoise"
state = "Diseased Samples"
genes.2 = modules.df.2[modules.df.2$modules==mod1,]$genes

ego_bp.2 <- enrichGO(
  gene         = genes.2, 
  OrgDb        = org.Hs.eg.db, 
  keyType      = "SYMBOL", 
  ont          = "BP",        # Choose BP (Biological Process), MF, or CC
  pAdjustMethod = "BH",       # Benjamini-Hochberg correction
  pvalueCutoff = 0.05, 
  qvalueCutoff = 0.05
)

# View top enriched GO terms
head(ego_bp.2)
write.csv(as.data.frame(ego_bp.2), paste0(mod1,"_diseased_modules.csv"))


# Example barplot
title = sprintf("Top GO BP Terms for %s", state)
gplot <- barplot(ego_bp.2, showCategory=10, title=title, ) + 
  geom_bar(stat="identity", color="black") +
         scale_fill_gradient(low = mod1, high = "gray90")  # Change color gradient

print(gplot)
```

## 3.2 Nonshock vs Shock

```{r}
modules.df = read.csv("modules/modules_nonshock_scalefree5.csv", header = T)
modules.df.2 = read.csv("modules/modules_shock_scalefree8.csv", header = T)
head(modules.df)
head(modules.df.2)
```

```{r}
mod1 = "brown"
state = "Nonshock Samples"
genes = modules.df[modules.df$modules==mod1,]$genes

ego_bp <- enrichGO(
  gene         = genes, 
  OrgDb        = org.Hs.eg.db, 
  keyType      = "SYMBOL", 
  ont          = "BP",        # Choose BP (Biological Process), MF, or CC
  pAdjustMethod = "BH",       # Benjamini-Hochberg correction
  pvalueCutoff = 0.05, 
  qvalueCutoff = 0.05
)

# View top enriched GO terms
head(ego_bp)
write.csv(as.data.frame(ego_bp), paste0(mod1,"_nonshock_modules.csv"))

# Example barplot
title = sprintf("Top GO BP Terms for %s", state)
gplot <- barplot(ego_bp, showCategory=10, title=title, ) + 
  geom_bar(stat="identity", color="black") +
  theme(axis.text.y = element_text(size = 8),
  panel.grid.major = element_blank(),   # Remove major gridlines
  panel.grid.minor = element_blank()) +    # Remove minor gridlines) +
  scale_fill_gradient(low = mod1, high = "gray90")  # Change color gradient

print(gplot)

mod1 = "coral1"
state = "Shock Samples"
genes.2 = modules.df.2[modules.df.2$modules==mod1,]$genes

ego_bp.2 <- enrichGO(
  gene         = genes.2, 
  OrgDb        = org.Hs.eg.db, 
  keyType      = "SYMBOL", 
  ont          = "BP",        # Choose BP (Biological Process), MF, or CC
  pAdjustMethod = "BH",       # Benjamini-Hochberg correction
  pvalueCutoff = 0.05, 
  qvalueCutoff = 0.05
)

# View top enriched GO terms
head(ego_bp.2)
write.csv(as.data.frame(ego_bp.2), paste0(mod1,"_shock_modules.csv"))

# Example barplot
title = sprintf("GO BP Terms for %s", state)
gplot <- barplot(ego_bp.2, showCategory=10, title=title, ) + 
  geom_bar(stat="identity", color="black") +
  theme(axis.text.y = element_text(size = 8),
  panel.grid.major = element_blank(),   # Remove major gridlines
  panel.grid.minor = element_blank()) +    # Remove minor gridlines +
  scale_fill_gradient(low = mod1, high = "gray90")  # Change color gradient

print(gplot)
```

```{r}
mod1 = "turquoise"
state = "Nonshock Samples"
genes = modules.df[modules.df$modules==mod1,]$genes

ego_bp <- enrichGO(
  gene         = genes, 
  OrgDb        = org.Hs.eg.db, 
  keyType      = "SYMBOL", 
  ont          = "BP",        # Choose BP (Biological Process), MF, or CC
  pAdjustMethod = "BH",       # Benjamini-Hochberg correction
  pvalueCutoff = 0.05, 
  qvalueCutoff = 0.05
)

# View top enriched GO terms
head(ego_bp)
write.csv(as.data.frame(ego_bp), paste0(mod1,"_nonshock_modules.csv"))

# Example barplot
title = sprintf("Top GO BP Terms for %s", state)
gplot <- barplot(ego_bp, showCategory=10, title=title, ) + 
  geom_bar(stat="identity", color="black") +
  theme(axis.text.y = element_text(size = 8),
  panel.grid.major = element_blank(),   # Remove major gridlines
  panel.grid.minor = element_blank()) +    # Remove minor gridlines) +
  scale_fill_gradient(low = mod1, high = "gray90")  # Change color gradient

print(gplot)

mod1 = "cyan"
state = "Shock Samples"
genes.2 = modules.df.2[modules.df.2$modules==mod1,]$genes

ego_bp.2 <- enrichGO(
  gene         = genes.2, 
  OrgDb        = org.Hs.eg.db, 
  keyType      = "SYMBOL", 
  ont          = "BP",        # Choose BP (Biological Process), MF, or CC
  pAdjustMethod = "BH",       # Benjamini-Hochberg correction
  pvalueCutoff = 0.05, 
  qvalueCutoff = 0.05
)

# View top enriched GO terms
head(ego_bp.2)
write.csv(as.data.frame(ego_bp.2), paste0(mod1,"_shock_modules.csv"))


# Example barplot
title = sprintf("GO BP Terms for %s", state)
gplot <- barplot(ego_bp.2, showCategory=10, title=title, ) + 
  geom_bar(stat="identity", color="black") +
  theme(axis.text.y = element_text(size = 8),
  panel.grid.major = element_blank(),   # Remove major gridlines
  panel.grid.minor = element_blank()) +    # Remove minor gridlines +
  scale_fill_gradient(low = mod1, high = "gray90")  # Change color gradient

print(gplot)
```

# 4 DEGs Identification: *limma* package

## 4.1 Healthy vs Diseased genes

```{r}
modules.df = read.csv("modules/modules_healthy_scalefree10.csv", header = T)
modules.df.2 = read.csv("modules/modules_diseased_scalefree6.csv", header = T)

healthy_modules = c("green", "grey", "yellow")
diseased_modules = c("magenta", "turquoise")

healthy_genes = unique(modules.df[modules.df$modules %in% healthy_modules,]$genes)
diseased_genes = unique(modules.df.2[modules.df.2$modules %in% diseased_modules,]$genes)
length(healthy_genes)
length(diseased_genes)
```

```{r}

```
